services:
  grafana:
    image: grafana/grafana-oss:13.0.2
    user: <UID>:<GID>
    volumes:
      - ./data:/var/lib/grafana
    networks:
      - reverse-proxy
    labels:
      # Traefik integration labels - start
      - "traefik.enable=true"
      - "traefik.http.services.grafana.loadBalancer.server.port=3000"
      - "traefik.http.routers.grafana.service=grafana"
      - "traefik.http.routers.grafana.tls.certresolver=cloudflare"
      - "traefik.http.routers.grafana.entrypoints=private-https"
      - "traefik.http.routers.grafana.rule=Host(`grafana.<DOMAIN_NAME>`)"
      # Traefik integration labels - end
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == <HOST_NAME>
networks:
  reverse-proxy:
    external: true
